'use client';
import Image from "next/image";
import React, { useState } from "react";

export default function BrocoliPage() {
  const [step, setStep] = useState(1);
  const [prompt, setPrompt] = useState("I want to bulk up");
  const [budget, setBudget] = useState(50);
  // Placeholder summary, in real app this would be generated by AI
  const summary =
    "You grocery trip is going to be protein filled, with vegetables and meat";

  return (
    <div className="min-h-screen flex flex-col items-center justify-between bg-[#FDE500] px-4 pt-6 pb-6 w-full max-w-md mx-auto">
      {/* Top bar (fake status bar for mobile look) */}
      <div className="w-full flex justify-between items-center mb-2">
        <span className="text-xs font-semibold tracking-wide">9:41</span>
        <div className="flex gap-1 items-center">
          <span className="inline-block w-1.5 h-1.5 bg-black rounded-full"></span>
          <span className="inline-block w-1.5 h-1.5 bg-black rounded-full"></span>
          <span className="inline-block w-1.5 h-1.5 bg-black rounded-full"></span>
        </div>
        <div className="flex gap-1 items-center">
          <span className="inline-block w-4 h-2 bg-black rounded-sm"></span>
          <span className="inline-block w-2 h-2 bg-black rounded-full"></span>
        </div>
      </div>
      {step === 1 ? (
        <>
          {/* Title and subtitle */}
          <div className="w-full flex flex-col items-start mt-2">
            <h1 className="text-5xl font-extrabold leading-none text-black">Create<br/>A Pod</h1>
            <p className="text-lg font-semibold text-black mt-2">Tell Mr Brocoli what you need</p>
          </div>
          {/* Mascot */}
          <div className="flex justify-center w-full my-6">
            <Image src="/brocoli.svg" alt="Mr Brocoli" width={132} height={137} priority />
          </div>
          {/* Input area */}
          <form
            className="w-full flex flex-col items-center flex-1"
            onSubmit={e => {
              e.preventDefault();
              setStep(2);
            }}
          >
            <textarea
              className="w-full min-h-[120px] rounded-2xl p-4 text-lg font-semibold text-black bg-white placeholder:text-black/60 focus:outline-none resize-none shadow-md"
              placeholder="I want to bulk up"
              value={prompt}
              onChange={e => setPrompt(e.target.value)}
            />
            <button
              type="submit"
              className="w-full mt-8 bg-black text-white text-lg font-bold py-3 rounded-full shadow-lg active:scale-95 transition-transform"
            >
              Generate a Plan
            </button>
          </form>
        </>
      ) : (
        <>
          {/* Plan Step */}
          <div className="w-full flex flex-col items-start mt-2">
            <h1 className="text-5xl font-extrabold leading-none text-black">Plan</h1>
            <p className="text-lg font-semibold text-black mt-2">Heaaar me out!</p>
          </div>
          <div className="w-full flex flex-col mt-6">
            <div className="flex items-end gap-2">
              <span className="text-5xl font-extrabold text-black">${budget}</span>
              <span className="text-lg font-bold text-black mb-1">Budget</span>
            </div>
            <div className="w-full mt-2 mb-4">
              <input
                type="range"
                min={10}
                max={200}
                step={1}
                value={budget}
                onChange={e => setBudget(Number(e.target.value))}
                className="w-full accent-black h-2 rounded-lg appearance-none bg-white shadow-md"
                style={{ accentColor: '#171717' }}
              />
            </div>
          </div>
          <div className="w-full flex-1 flex flex-col justify-between">
            <div className="relative w-full">
              <div className="w-full min-h-[120px] rounded-2xl p-4 text-lg font-semibold text-black bg-white shadow-md mb-4">
                {summary}
              </div>
              <div className="absolute right-0 bottom-[-40px]">
                <Image src="/brocoli.svg" alt="Mr Brocoli" width={110} height={114} />
              </div>
            </div>
            <button
              className="w-full mt-8 bg-black text-white text-lg font-bold py-3 rounded-full shadow-lg active:scale-95 transition-transform"
            >
              Generate Grocery List
            </button>
          </div>
        </>
      )}
    </div>
  );
} 